import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from "@/components/navigation/navbar";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";
import { auth } from "@/auth";
import { AuthProvider } from '@/context/AuthContext';
import LeftSideBar from "@/components/navigation/LeftSideBar";
import RightSideBar from "@/components/navigation/RightSideBar";
import 'devicon/devicon.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children} : {children : ReactNode}) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        
      <link 
      rel="stylesheet" 
      type='text/css' 
      href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
          
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <SessionProvider session={session}>
            <AuthProvider>
              <Navbar/>
              <div className="flex">
                <LeftSideBar/>
                    <div className="flex-1">
                      {children}
                    </div>
                  <RightSideBar/>
               </div>
              
              <Toaster/>
              
            </AuthProvider>
            
          </SessionProvider>
        </ThemeProvider>
        
      </body>
    </html>
  );
}
